# This is a basic workflow to help you get started with Actions
name: Demo workflow
# Controls when the workflow will run
on: [push]
jobs:
  hello-world-job:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
# Sequence of tasks that will be executed as part of the job
    steps:
# Checks-out the repository
    - uses: actions/checkout@v2
# Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
